# Generated by Django 2.1.10 on 2019-08-27 04:33

import api.models
from django.db import migrations, models
import django.db.models.deletion


# エラー回避用
def upload_to():
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=upload_to)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='alarmtask',
            name='sound_index',
        ),
        migrations.AlterField(
            model_name='alarmtask',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='alarmtask',
            name='sound',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Sound'),
            preserve_default=False,
        ),
    ]
